database:
  host: '138.246.233.217'

cluster:
  apihost: 138.246.233.207:31001
  auth: 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP

server:
  invoker:
    type: openwhisk
    params:
      name: invoker
      file: /Users/andreas/workspace/thesis-code/functions/openwhisk/invoker/main.py
      image: andreasgrafberger/fedless-openwhisk
      memory: 2048
      timeout: 60000

  evaluator:
    type: openwhisk
    params:
      name: evaluator
      file: /Users/andreas/workspace/thesis-code/functions/openwhisk/evaluator/main.py
      image: andreasgrafberger/fedless-openwhisk
      memory: 2048
      timeout: 60000

  aggregator:
    type: openwhisk
    params:
      name: aggregator
      file: /Users/andreas/workspace/thesis-code/functions/openwhisk/aggregator/main.py
      image: andreasgrafberger/fedless-openwhisk
      memory: 2024
      timeout: 60000


clients:
  hyperparams:
    epochs: 1
    batch_size: 10
    optimizer:
      class_name: "Adam"
      config:
        name: "Adam"
        learning_rate: 0.001
  functions:
    - function:
        replicas: 50
        params:
          endpoint: https://138.246.233.207:31001/api/v1/web/guest/default/client.json
          self_signed_cert: true
          token: "/JCH1voWi6m/kFr+hbrCo9N2F1HPUXbBD1W2SxXS"
          type: openwhisk-web
        type: openwhisk-web
