service: client

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: eu-central-1
  memorySize: 2048
  timeout: 30 # Note: API Gateway current maximum is 30 seconds
  ecr:
    images:
      baseimage:
        path: .
  apiGateway:
    apiKeys:
      - invoker-key
    usagePlan:
      quota:
        limit: 2000
        period: MONTH
      throttle:
        rateLimit: 100

functions:
  hello:
    image: baseimage
    events:
      - http:
          path: federated/client
          method: post
          integration: lambda-proxy
          private: true
