name: Lint and Test

on: [ push, pull_request ]

jobs:
  python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Lint  with Black
        run: black --check .

      - name: Unit Tests
        run: pytest

      - name: Integration Tests
        run: pytest -m "integ" --no-cov

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  deploy-python:
    name: Deploy Python Package
    needs: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fedless-dist
          path: ./dist/*.whl

  build-push-base-images:
    name: Build and Deploy Docker Images
    needs: deploy-python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: fedless-dist
          path: dist/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push lambda base image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./images/lambda/base/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fedless:lambda
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push openwhisk base image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./images/openwhisk/base/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fedless-openwhisk:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: .venv node_modules